services:
  - type: web
    name: alura-agente
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
 